create table message (
    id int8 generated by default as identity,
    filename varchar(255),
    tag varchar(255),
    text varchar(2048) not null,
    user_id int8,
    primary key (id)
);

create table usrs (
    id int8 generated by default as identity,
    activation_code varchar(255),
    email varchar(255),
    is_active boolean not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

create table usrs_roles (
    user_id int8 not null,
    roles varchar(255)
);

alter table if exists message
    add constraint message_usrs_fk
    foreign key (user_id) references usrs;

alter table if exists usrs_roles
    add constraint usrs_roles_usrs_fk
    foreign key (user_id) references usrs;